# Generated by Django 4.2.1 on 2023-08-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
